#!/usr/bin/env python3
"""TTF -> LVGL v9 C 폰트 (필요한 글자만 서브셋)

node 기반 lv_font_conv 없이 freetype-py 로 지정한 문자들만 렌더해
LVGL 의 lv_font_fmt_txt 포맷 C 소스를 만든다. 4bpp(16단계) 안티에일리어싱.

  ./font_conv.py -i korean.ttf -o lv_font_kr_28.c -n lv_font_kr_28 \
                 -s 28 --text "카세트 시스템 정보 ..."

  # 자주 쓰는 서브셋을 파일로
  ./font_conv.py -i korean.ttf -o out.c -n name -s 28 --textfile chars.txt
"""

import argparse
import sys

import freetype


ASCII = "".join(chr(c) for c in range(0x20, 0x7F))


def collect_chars(args):
    chars = set(ASCII)
    if args.text:
        chars |= set(args.text)
    if args.textfile:
        with open(args.textfile, encoding="utf-8") as f:
            chars |= set(f.read())
    chars.discard("\n")
    chars.discard("\r")
    chars.discard("\t")
    return sorted(chars, key=ord)


class Glyph:
    __slots__ = ("cp", "adv_w", "box_w", "box_h", "ofs_x", "ofs_y", "bits", "bmp_index")


def render(face, cp):
    face.load_char(cp, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
    g = face.glyph
    bmp = g.bitmap
    w, h, pitch = bmp.width, bmp.rows, bmp.pitch
    buf = bmp.buffer

    gl = Glyph()
    gl.cp = ord(cp)
    gl.adv_w = round(g.advance.x / 64.0 * 16)
    gl.box_w = w
    gl.box_h = h
    gl.ofs_x = g.bitmap_left
    gl.ofs_y = g.bitmap_top - h

    # 4bpp 연속 비트스트림 (MSB first)
    data = bytearray()
    acc = 0
    nbits = 0
    for r in range(h):
        base = r * pitch
        for c in range(w):
            v4 = buf[base + c] >> 4
            acc = (acc << 4) | v4
            nbits += 4
            if nbits == 8:
                data.append(acc & 0xFF)
                acc = 0
                nbits = 0
    if nbits:
        data.append((acc << (8 - nbits)) & 0xFF)
    gl.bits = bytes(data)
    return gl


def emit(glyphs, name, line_height, base_line, out):
    w = out.write

    w("/* Generated by tools/python/font_conv.py (LVGL v9 fmt_txt, 4bpp) */\n")
    w('#include "lvgl/lvgl.h"\n\n')
    w("#ifndef LV_ATTRIBUTE_LARGE_CONST\n#define LV_ATTRIBUTE_LARGE_CONST\n#endif\n\n")

    # --- glyph bitmap ---
    w("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {\n")
    idx = 0
    for gl in glyphs:
        gl.bmp_index = idx
        if gl.bits:
            w("    /* U+%04X */ " % gl.cp)
            w(",".join("0x%02x" % b for b in gl.bits))
            w(",\n")
            idx += len(gl.bits)
    w("};\n\n")

    # --- glyph descriptors (id 0 reserved) ---
    w("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n")
    w("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},\n")
    for gl in glyphs:
        bi = gl.bmp_index if gl.bits else 0
        w("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d},\n"
          % (bi, gl.adv_w, gl.box_w, gl.box_h, gl.ofs_x, gl.ofs_y))
    w("};\n\n")

    # --- cmap : 하나의 SPARSE_TINY 로 전 범위 커버 ---
    cps = [gl.cp for gl in glyphs]
    lo, hi = cps[0], cps[-1]
    span = hi - lo + 1
    if span >= 0x10000:
        print("경고: 코드포인트 범위가 65535 를 넘어 SPARSE_TINY 로 못 담습니다.", file=sys.stderr)

    w("static const uint16_t unicode_list[] = {\n    ")
    w(", ".join(str(cp - lo) for cp in cps))
    w("\n};\n\n")

    w("static const lv_font_fmt_txt_cmap_t cmaps[] = {\n")
    w("    {\n")
    w("        .range_start = %d, .range_length = %d, .glyph_id_start = 1,\n" % (lo, span))
    w("        .unicode_list = unicode_list, .glyph_id_ofs_list = NULL,\n")
    w("        .list_length = %d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY\n" % len(cps))
    w("    }\n};\n\n")

    # --- dsc ---
    w("static const lv_font_fmt_txt_dsc_t font_dsc = {\n")
    w("    .glyph_bitmap = glyph_bitmap,\n")
    w("    .glyph_dsc = glyph_dsc,\n")
    w("    .cmaps = cmaps,\n")
    w("    .kern_dsc = NULL,\n")
    w("    .kern_scale = 0,\n")
    w("    .cmap_num = 1,\n")
    w("    .bpp = 4,\n")
    w("    .kern_classes = 0,\n")
    w("    .bitmap_format = 0,\n")
    w("};\n\n")

    # --- public font ---
    w("const lv_font_t %s = {\n" % name)
    w("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,\n")
    w("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n")
    w("    .line_height = %d,\n" % line_height)
    w("    .base_line = %d,\n" % base_line)
    w("    .subpx = LV_FONT_SUBPX_NONE,\n")
    w("    .underline_position = -2,\n")
    w("    .underline_thickness = 1,\n")
    w("    .dsc = &font_dsc,\n")
    w("};\n")


def main():
    ap = argparse.ArgumentParser(description="TTF -> LVGL C 폰트 서브셋")
    ap.add_argument("-i", "--input", required=True, help="TTF/OTF 경로")
    ap.add_argument("-o", "--output", required=True, help="출력 .c")
    ap.add_argument("-n", "--name", required=True, help="lv_font_t 심볼 이름")
    ap.add_argument("-s", "--size", type=int, required=True, help="픽셀 크기")
    ap.add_argument("--text", help="포함할 문자들")
    ap.add_argument("--textfile", help="포함할 문자를 담은 텍스트 파일")
    args = ap.parse_args()

    face = freetype.Face(args.input)
    face.set_pixel_sizes(0, args.size)

    line_height = face.size.height >> 6
    ascender    = face.size.ascender >> 6
    descender   = face.size.descender >> 6      # 보통 음수
    base_line   = -descender
    if line_height <= 0:
        line_height = ascender - descender

    chars = collect_chars(args)
    glyphs = [render(face, c) for c in chars]

    total = sum(len(g.bits) for g in glyphs)
    with open(args.output, "w", encoding="utf-8") as f:
        emit(glyphs, args.name, line_height, base_line, f)

    print("생성 : %s" % args.output)
    print("  글자 %d 개, 비트맵 %d bytes, line_height %d, base_line %d"
          % (len(glyphs), total, line_height, base_line))


if __name__ == "__main__":
    main()
